// Generated by Website Factory (GaLaBau vertical). Update via the factory pipeline, not by hand.

export type GalabauUnit = "qm" | "lfm" | "stk" | "pauschal";

export type GalabauServiceKey =
  | "gartenneugestaltung"
  | "pflasterarbeiten"
  | "terrassenbau"
  | "gartenpflege"
  | "zaun-sichtschutz"
  | "bewaesserung"
  | "baumpflege"
  | "gewerbeflaechen";

export type GalabauService = {
  key: GalabauServiceKey;
  slug: string;
  label: string;
  navLabel: string;
  cta: string;
  unit: GalabauUnit;
  teaser: string;
  intro: string;
  bullets: string[];
  ablauf: { title: string; text: string }[];
  faq: { q: string; a: string }[];
  image: string;
  estimate: { minPerUnit: number; maxPerUnit: number; baseMin: number };
  seo: { title: string; description: string };
};

export type GalabauBudgetBand = {
  id: string;
  label: string;
  min: number;
  max: number | null;
};

export type GalabauConfig = {
  company: {
    name: string;
    city: string;
    foundedYear: string;
    teamSize: string;
    machines: string;
  };
  claim: string;
  heroSubline: string;
  services: GalabauService[];
  serviceArea: {
    centerCity: string;
    radiusKm: number;
    note: string;
    plzPrefixes: string[];
    borderPlzPrefixes: string[];
    places: string[];
    /** Map centre from the Google profile. Without it the map is skipped. */
    center?: { lat: number; lng: number };
  };
  contact: {
    phone: string;
    phoneLink: string;
    whatsapp: string;
    whatsappLink: string;
    whatsappPrefill: string;
    email: string;
    leadEmail: string;
  };
  estimator: {
    enabled: boolean;
    minProjectEur: number;
    currency: string;
    roundingStep: number;
    disclaimer: string;
    sizeThresholds: { klein: number; mittel: number };
    surcharges: { hanglage: number; schwererZugang: number; rueckbauBestand: number };
    budgetBands: GalabauBudgetBand[];
    realismQuestion: string;
    realismOptions: { id: string; label: string }[];
  };
  recruiting: {
    enabled: boolean;
    headline: string;
    teaser: string;
    intro: string;
    roles: string[];
    benefits: string[];
  };
  trust: {
    seals: { label: string; note: string }[];
    usps: { label: string; text: string }[];
  };
  assistant: {
    enabled: boolean;
    photoUploadMaxFiles: number;
    photoUploadMaxMb: number;
    consentText: string;
    responsePromise: string;
  };
};

export const galabau: GalabauConfig = {
  "company": {
    "name": "Garten- und Landschaftsbau Gashi",
    "city": "Leimen",
    "foundedYear": "",
    "teamSize": "",
    "machines": ""
  },
  "claim": "Pflaster, Terrasse, Rollrasen. Aus Leimen.",
  "heroSubline": "Gartengestaltung, Pflasterarbeiten, Mauern und Gartenpflege für Leimen, Heidelberg und den Rhein-Neckar-Raum. Erstberatung und Besichtigung sind kostenlos.",
  "services": [
    {
      "key": "gartenneugestaltung",
      "slug": "gartenneugestaltung",
      "label": "Gartenneugestaltung",
      "navLabel": "Gartengestaltung",
      "cta": "Projekt planen lassen",
      "unit": "qm",
      "teaser": "Vom Rohgrundstück zur fertigen Anlage: Erdarbeiten, Wege, Mauern, Rollrasen und Beete in einem Zug.",
      "intro": "Bei einer Neuanlage hängt alles zusammen: Geländemodellierung, Entwässerung, Wege, Mauern und erst ganz zum Schluss Rasen und Bepflanzung. Wir übernehmen die Gewerke selbst, statt sie an wechselnde Subunternehmer zu verteilen. Die Erstberatung samt Besichtigung vor Ort kostet Sie nichts.",
      "bullets": [
        "Erdarbeiten und Geländemodellierung, auch Teichbau",
        "Wege und Sitzplätze aus Pflaster, Naturstein oder Ziersplitt",
        "Gabionen, Trockenmauern und Böschungssicherung",
        "Rollrasen, Beete und Bewässerung zum Abschluss",
        "Aushub und alter Bestand werden von uns abgefahren"
      ],
      "ablauf": [
        {
          "title": "Anfrage",
          "text": "Sie schildern Fläche, Zustand und Wunsch über den Projekt-Assistenten, idealerweise mit Fotos."
        },
        {
          "title": "Kostenlose Besichtigung",
          "text": "Wir kommen vorbei, messen auf und prüfen Zugang, Boden und Gefälle. Beratung und Ortstermin sind kostenfrei."
        },
        {
          "title": "Planung & Angebot",
          "text": "Sie bekommen eine nachvollziehbare Planung mit Positionen, nicht nur eine Endsumme."
        },
        {
          "title": "Ausführung",
          "text": "Feste Bauzeit, ein Ansprechpartner, saubere Übergabe inklusive Pflegehinweisen."
        }
      ],
      "faq": [
        {
          "q": "Was kostet eine Gartenneugestaltung?",
          "a": "Das hängt stark von Fläche, Untergrund, Zugang und Material ab. Deshalb nennen wir online nur grobe Orientierungsrahmen und den verbindlichen Preis erst nach dem Aufmaß vor Ort. Die Besichtigung selbst ist kostenlos."
        },
        {
          "q": "Wie lange dauert so ein Projekt?",
          "a": "Kleinere Umgestaltungen dauern wenige Tage, komplette Neuanlagen mit Erdarbeiten, Mauer und Rollrasen meist mehrere Wochen. Den Zeitrahmen legen wir vor Baubeginn fest."
        }
      ],
      "image": "/assets/leistungen/gartenneugestaltung-mit-beleuchtung.webp",
      "estimate": {
        "minPerUnit": 120,
        "maxPerUnit": 320,
        "baseMin": 4000
      },
      "seo": {
        "title": "Gartenneugestaltung in Leimen | Garten- und Landschaftsbau Gashi",
        "description": "Gartenneugestaltung mit Planung, Erdarbeiten, Wegen und Bepflanzung. Aufmaß vor Ort, klare Positionen, feste Bauzeit."
      }
    },
    {
      "key": "pflasterarbeiten",
      "slug": "pflasterarbeiten",
      "label": "Pflasterarbeiten",
      "navLabel": "Pflaster",
      "cta": "Fläche einschätzen lassen",
      "unit": "qm",
      "teaser": "Einfahrt, Hofflächen, Wege und Treppen mit tragfähigem Unterbau und sauberer Entwässerung.",
      "intro": "Pflaster hält so lange, wie der Unterbau es zulässt. Wir bauen die Tragschicht auf die tatsächliche Belastung aus, planen das Gefälle mit und lösen die Entwässerung, bevor der erste Stein liegt. Viele Hanglagen rund um Leimen und Heidelberg brauchen dabei zusätzlich Stufen oder eine Stützmauer, das planen wir gleich mit.",
      "bullets": [
        "Einfahrt, Zufahrt, Hof, Wege und Hauszugänge",
        "Unterbau nach Belastung: PKW, Wohnmobil oder Lieferverkehr",
        "Blockstufen und Treppenanlagen für Hanggrundstücke",
        "Auswahl aus verschiedenen Pflaster-, Naturstein- und Kiessorten",
        "Entwässerung, Rinnen und Anschluss an Bestandsflächen"
      ],
      "ablauf": [
        {
          "title": "Fläche melden",
          "text": "Quadratmeter grob schätzen oder Fotos schicken, wir rechnen die Fläche nach."
        },
        {
          "title": "Aufbau festlegen",
          "text": "Wir klären Belastung, Untergrund und Entwässerung und wählen den passenden Aufbau."
        },
        {
          "title": "Angebot",
          "text": "Positionen für Aushub, Entsorgung, Tragschicht, Material und Einbau, getrennt ausgewiesen."
        },
        {
          "title": "Einbau",
          "text": "Aushub, Verdichtung, Verlegung, Abrütteln und Verfugen mit sauberer Baustellenübergabe."
        }
      ],
      "faq": [
        {
          "q": "Muss die alte Fläche raus?",
          "a": "Meist ja. Ein neues Pflaster auf altem, gesetztem Unterbau bekommt früher oder später Spurrillen. Wir prüfen den Bestand und sagen offen, ob ein Rückbau nötig ist."
        },
        {
          "q": "Wie viel Gefälle braucht die Fläche?",
          "a": "Als Faustwert rund zwei Prozent, weg vom Gebäude. Wo das nicht geht, planen wir Rinnen oder Versickerung ein."
        }
      ],
      "image": "/assets/leistungen/pflasterarbeiten-terrasse.webp",
      "estimate": {
        "minPerUnit": 90,
        "maxPerUnit": 210,
        "baseMin": 3000
      },
      "seo": {
        "title": "Pflasterarbeiten in Leimen | Garten- und Landschaftsbau Gashi",
        "description": "Pflasterarbeiten für Einfahrt, Wege und Hofflächen: tragfähiger Unterbau, geplante Entwässerung, saubere Randeinfassung."
      }
    },
    {
      "key": "terrassenbau",
      "slug": "terrassenbau",
      "label": "Terrassenbau",
      "navLabel": "Terrasse",
      "cta": "Terrasse anfragen",
      "unit": "qm",
      "teaser": "Terrassen aus Naturstein, Keramik oder Holz, mit Unterbau, Randabschluss und Übergang zum Garten.",
      "intro": "Die Terrasse ist der Teil des Gartens, der täglich benutzt wird. Materialwahl, Untergrund und Entwässerung entscheiden darüber, wie sie nach fünf Jahren aussieht, nicht das Muster im Prospekt. Wir bauen die Terrasse zusammen mit dem Zugang und der angrenzenden Fläche, damit die Höhen am Ende stimmen.",
      "bullets": [
        "Materialien: Keramik, Naturstein, Betonplatten, Holz und WPC",
        "Unterbau: Splittbett, Stelzlager oder Punktfundamente",
        "Anschluss an Treppe, Weg und Rasenkante in einem Zug",
        "Sichtschutz und Gabionen als Abgrenzung auf Wunsch",
        "Pflegehinweise je nach Material bei der Übergabe"
      ],
      "ablauf": [
        {
          "title": "Wunsch klären",
          "text": "Größe, Nutzung, Sonne und gewünschtes Material, gern mit Inspirationsbildern."
        },
        {
          "title": "Untergrund prüfen",
          "text": "Wir schauen uns Anschlusshöhen, Türschwellen und Entwässerung vor Ort an."
        },
        {
          "title": "Angebot",
          "text": "Aufbau, Material und Zusatzleistungen wie Beleuchtung getrennt kalkuliert."
        },
        {
          "title": "Bau",
          "text": "Unterbau, Belag, Randabschluss, Reinigung und Übergabe."
        }
      ],
      "faq": [
        {
          "q": "Holz oder Keramik?",
          "a": "Holz ist warm und lebendig, braucht aber Pflege. Keramik und Naturstein sind pflegeleicht und farbstabil. Wir bringen Muster zum Ortstermin mit, bevor Sie sich festlegen."
        },
        {
          "q": "Geht das auch auf einer bestehenden Platte?",
          "a": "Oft ja, mit Stelzlagern. Voraussetzung ist eine ausreichende Aufbauhöhe an der Tür und ein funktionierendes Gefälle."
        }
      ],
      "image": "/assets/leistungen/terrassenbau-grossformatplatten-01.webp",
      "estimate": {
        "minPerUnit": 140,
        "maxPerUnit": 380,
        "baseMin": 3500
      },
      "seo": {
        "title": "Terrassenbau in Leimen | Garten- und Landschaftsbau Gashi",
        "description": "Terrassenbau mit Naturstein, Keramik oder Holz: geplanter Unterbau, Entwässerung, Sichtschutz und Beleuchtung."
      }
    },
    {
      "key": "gartenpflege",
      "slug": "gartenpflege",
      "label": "Gartenpflege",
      "navLabel": "Pflege",
      "cta": "Pflege anfragen",
      "unit": "qm",
      "teaser": "Rasen, Hecken, Baumschnitt und Rollrasen, einmalig oder mit festen Terminen über die Saison.",
      "intro": "Pflege ist planbar. Wer feste Termine hat, spart den jährlichen Rückschnitt-Notfall. Wir machen beides: den einmaligen Einsatz, wenn der Garten aus dem Ruder gelaufen ist, und die laufende Pflege über die Saison, für private Gärten ebenso wie für Wohnanlagen.",
      "bullets": [
        "Rasenpflege: Mähen, Vertikutieren, Nachsaat, Düngung",
        "Rollrasen verlegen statt monatelang auf Ansaat warten",
        "Heckenpflege, Formschnitt und Rückschnitt von Sträuchern",
        "Baumschnitt und Baumfällung nach Absprache",
        "Einmalpflege für verwilderte Gärten inklusive Abtransport"
      ],
      "ablauf": [
        {
          "title": "Bestand ansehen",
          "text": "Fotos oder Ortstermin, damit der Aufwand realistisch eingeschätzt wird."
        },
        {
          "title": "Umfang festlegen",
          "text": "Einmaliger Einsatz oder feste Turnusse, mit klarer Liste, was enthalten ist."
        },
        {
          "title": "Termine",
          "text": "Feste Turnusse statt Zufall, Sie wissen wann wir kommen."
        },
        {
          "title": "Pflege",
          "text": "Ausführung inklusive Abtransport des Schnittguts."
        }
      ],
      "faq": [
        {
          "q": "Was kostet die laufende Pflege?",
          "a": "Das richtet sich nach Fläche, Heckenlänge und Turnus. Nach einem kurzen Blick auf die Fläche nennen wir einen festen Betrag je Einsatz oder für die Saison."
        },
        {
          "q": "Wann wird die Hecke geschnitten?",
          "a": "Der Formschnitt erfolgt außerhalb der gesetzlichen Schonzeit. Radikale Rückschnitte sind vom 1. März bis 30. September nicht zulässig."
        }
      ],
      "image": "/assets/leistungen/gartenpflege-heckenschnitt.webp",
      "estimate": {
        "minPerUnit": 3,
        "maxPerUnit": 12,
        "baseMin": 350
      },
      "seo": {
        "title": "Gartenpflege in Leimen | Garten- und Landschaftsbau Gashi",
        "description": "Gartenpflege als Einmalpflege oder Pflegevertrag: Rasen, Heckenschnitt, Beete und Saisonarbeiten mit festen Terminen."
      }
    },
    {
      "key": "zaun-sichtschutz",
      "slug": "zaun-sichtschutz",
      "label": "Zaun, Mauer & Sichtschutz",
      "navLabel": "Zaun & Mauer",
      "cta": "Sichtschutz anfragen",
      "unit": "lfm",
      "teaser": "Gabionen, Trockenmauern, Holzzäune und Doppelstabmatten, kalkuliert nach laufenden Metern.",
      "intro": "Abgrenzung heißt bei uns nicht automatisch Zaun. Gabionenwände und Trockenmauern nehmen gleichzeitig Höhenunterschiede auf, was auf den Hanggrundstücken der Region oft die bessere Lösung ist. Entscheidend sind Höhe, Fundament und Grenzverlauf, und wir sagen vorab, wo eine Genehmigung oder eine Abstimmung mit dem Nachbarn nötig ist.",
      "bullets": [
        "Gabionenwände als Sichtschutz und Böschungssicherung",
        "Trockenmauern und gemauerte Stützwände",
        "Holzzäune, Doppelstabmatten, WPC und Aluminium",
        "Kalkulation nach laufenden Metern inklusive Pfosten und Fundament",
        "Hinweise zu Grenzbebauung, Höhe und örtlichen Satzungen"
      ],
      "ablauf": [
        {
          "title": "Meter schätzen",
          "text": "Grobe Länge und gewünschte Höhe genügen für die erste Einordnung."
        },
        {
          "title": "Grenze und Höhen klären",
          "text": "Wir prüfen Verlauf, Untergrund, Höhenunterschied und ob eine Genehmigung nötig ist."
        },
        {
          "title": "Angebot",
          "text": "Material, Pfosten, Fundamente und Tore als getrennte Positionen."
        },
        {
          "title": "Montage",
          "text": "Fundamente setzen, ausrichten, montieren, Baustelle räumen."
        }
      ],
      "faq": [
        {
          "q": "Wie hoch darf der Sichtschutz sein?",
          "a": "Das regeln Landesrecht und örtliche Satzung, häufig sind an der Grenze rund 1,80 m ohne Genehmigung möglich. Wir prüfen den konkreten Fall vor der Montage."
        },
        {
          "q": "Brauche ich Fundamente?",
          "a": "Bei Gabionen, Sichtschutzwänden und Toren ja. Bei leichten Zäunen genügen oft Einschlaghülsen, das entscheidet der Untergrund."
        }
      ],
      "image": "/assets/leistungen/zaun-und-sichtschutz.webp",
      "estimate": {
        "minPerUnit": 90,
        "maxPerUnit": 320,
        "baseMin": 1200
      },
      "seo": {
        "title": "Zaun, Mauer & Sichtschutz in Leimen | Garten- und Landschaftsbau Gashi",
        "description": "Gabionen, Trockenmauern, Holzzäune und Doppelstabmatten nach laufenden Metern, mit Fundament und Hinweisen zur Genehmigung."
      }
    },
    {
      "key": "bewaesserung",
      "slug": "bewaesserung",
      "label": "Beregnungsanlagen",
      "navLabel": "Beregnung",
      "cta": "Beregnung prüfen",
      "unit": "qm",
      "teaser": "Automatische Beregnung für Rasen und Beete, von der Auslegung bis zum Einwintern.",
      "intro": "Beregnungsanlagen gehören seit Langem zu unserem Programm. Eine automatische Anlage spart Wasser, weil sie früh morgens und nach Bedarf läuft. Wichtig ist die Auslegung: Druck, Durchfluss und Kreise müssen zusammenpassen, sonst bleiben einzelne Ecken trocken, während andere absaufen.",
      "bullets": [
        "Planung nach Druck, Durchfluss und Flächenzuschnitt",
        "Getrennte Kreise für Rasen, Beete und Tropfbewässerung",
        "Steuerung mit Regensensor oder App-Anbindung",
        "Nachrüstung in bestehende Gärten mit minimalem Aufgraben",
        "Wartung: Frühjahrsinbetriebnahme und Einwintern"
      ],
      "ablauf": [
        {
          "title": "Fläche & Wasser",
          "text": "Wir brauchen Flächengröße sowie Druck und Durchfluss am Hausanschluss."
        },
        {
          "title": "Auslegung",
          "text": "Kreise, Regner und Tropflinien werden auf die Fläche gerechnet."
        },
        {
          "title": "Angebot",
          "text": "Material, Verlegung und Steuerung transparent aufgeschlüsselt."
        },
        {
          "title": "Einbau",
          "text": "Verlegen, Einregulieren, Programmierung und Einweisung."
        }
      ],
      "faq": [
        {
          "q": "Muss der Rasen dafür raus?",
          "a": "Nein. Wir verlegen mit einem Verlegepflug, die Schnitte wachsen in der Regel innerhalb weniger Wochen zu."
        },
        {
          "q": "Was kostet die Wartung?",
          "a": "Inbetriebnahme und Einwintern sind planbare Pauschalen, die wir mit dem Angebot ausweisen."
        }
      ],
      "image": "/assets/leistungen/bewaesserung-rasen-und-beete.webp",
      "estimate": {
        "minPerUnit": 12,
        "maxPerUnit": 35,
        "baseMin": 1800
      },
      "seo": {
        "title": "Beregnungsanlagen in Leimen | Garten- und Landschaftsbau Gashi",
        "description": "Automatische Beregnung für Rasen und Beete: Planung nach Druck und Durchfluss, Steuerung, Nachrüstung und Wartung."
      }
    }
  ],
  "serviceArea": {
    "centerCity": "Leimen",
    "radiusKm": 40,
    "note": "Wir arbeiten im Umkreis von rund 40 km um Leimen, also im Rhein-Neckar-Raum zwischen Heidelberg, Mannheim, Wiesloch und Sinsheim. Liegt Ihr Projekt außerhalb, sagen wir Ihnen offen, ob sich die Anfahrt für den Umfang rechnet, statt Sie hinzuhalten.",
    "plzPrefixes": [
      "69",
      "68"
    ],
    "borderPlzPrefixes": [
      "64",
      "67",
      "74",
      "75",
      "76"
    ],
    "places": [
      "Leimen",
      "Heidelberg",
      "Nußloch",
      "Sandhausen",
      "Wiesloch",
      "Walldorf",
      "Eppelheim",
      "Dossenheim",
      "Neckargemünd",
      "Schwetzingen",
      "Mannheim",
      "Sinsheim"
    ],
    "center": { "lat": 49.3446671, "lng": 8.6884465 }
  },
  "contact": {
    "phone": "0172 4787238",
    "phoneLink": "tel:+491724787238",
    "whatsapp": "0172 4787238",
    "whatsappLink": "https://wa.me/491724787238",
    "whatsappPrefill": "Hallo Garten- und Landschaftsbau Gashi, ich habe eine Frage zu einem Gartenprojekt in ",
    "email": "info@gala-gashi.de",
    "leadEmail": "info@gala-gashi.de"
  },
  "estimator": {
    "enabled": true,
    "minProjectEur": 2500,
    "currency": "EUR",
    "roundingStep": 500,
    "disclaimer": "Alle Angaben sind eine unverbindliche Orientierung, kein Angebot. Der tatsächliche Preis hängt von Boden, Unterbau, Zugang, Entwässerung, Material und Ausführung ab und steht erst nach dem Aufmaß vor Ort fest.",
    "sizeThresholds": {
      "klein": 5000,
      "mittel": 20000
    },
    "surcharges": {
      "hanglage": 0.15,
      "schwererZugang": 0.12,
      "rueckbauBestand": 0.1
    },
    "budgetBands": [
      {
        "id": "bis-5k",
        "label": "bis 5.000 €",
        "min": 0,
        "max": 5000
      },
      {
        "id": "5-15k",
        "label": "5.000 – 15.000 €",
        "min": 5000,
        "max": 15000
      },
      {
        "id": "15-30k",
        "label": "15.000 – 30.000 €",
        "min": 15000,
        "max": 30000
      },
      {
        "id": "30-60k",
        "label": "30.000 – 60.000 €",
        "min": 30000,
        "max": 60000
      },
      {
        "id": "ab-60k",
        "label": "mehr als 60.000 €",
        "min": 60000,
        "max": null
      },
      {
        "id": "unklar",
        "label": "Noch unklar",
        "min": 0,
        "max": null
      }
    ],
    "realismQuestion": "Wäre dieser grobe Rahmen für Sie grundsätzlich realistisch?",
    "realismOptions": [
      {
        "id": "passt",
        "label": "Ja, das passt so"
      },
      {
        "id": "guenstiger",
        "label": "Überraschend günstig"
      },
      {
        "id": "zu-hoch",
        "label": "Zu hoch"
      },
      {
        "id": "unklar",
        "label": "Noch unklar"
      }
    ]
  },
  "recruiting": {
    "enabled": true,
    "headline": "Landschaftsgärtner, Helfer oder Quereinsteiger?",
    "teaser": "In 60 Sekunden bewerben. Ohne Lebenslauf, ohne Anschreiben.",
    "intro": "Wir sind ein kleiner Betrieb aus Leimen und arbeiten im Rhein-Neckar-Raum. Pflasterflächen, Mauern, Rollrasen, Pflege: alles selbst, nichts an Subunternehmer abgegeben. Wer mitarbeitet, sieht abends, was am Tag entstanden ist. Erzählen Sie uns kurz, was Sie können, den Rest klären wir am Telefon.",
    "roles": [
      "Landschaftsgärtner/in",
      "Helfer/in Garten- und Landschaftsbau",
      "Pflasterer/in",
      "Quereinsteiger/in",
      "Auszubildende/r"
    ],
    "benefits": [
      "Baustellen in der Region, abends sind Sie zu Hause",
      "Kleines festes Team statt wechselnder Kolonnen",
      "Alle Gewerke im Haus, von Erdarbeiten bis Beregnung",
      "Der Chef ist selbst auf der Baustelle, Entscheidungen fallen direkt",
      "Pünktliche Bezahlung, Arbeitszeit Montag bis Freitag"
    ]
  },
  "trust": {
    "seals": [],
    "usps": [
      {
        "label": "Beratung kostet nichts",
        "text": "Erstgespräch und Besichtigung vor Ort sind kostenfrei, auch wenn daraus kein Auftrag wird."
      },
      {
        "label": "Inhaber auf der Baustelle",
        "text": "Xhemo Gashi nimmt das Aufmaß selbst und ist während der Bauzeit Ihr Ansprechpartner."
      },
      {
        "label": "Alles aus einer Hand",
        "text": "Erdarbeiten, Pflaster, Mauer, Rollrasen und Beregnung machen wir selbst statt über Subunternehmer."
      }
    ]
  },
  "assistant": {
    "enabled": true,
    "photoUploadMaxFiles": 6,
    "photoUploadMaxMb": 8,
    "consentText": "Ich bin damit einverstanden, dass meine Angaben zur Bearbeitung meiner Anfrage gespeichert und verarbeitet werden. Die Daten werden nicht an Dritte weitergegeben.",
    "responsePromise": "Wir melden uns in der Regel innerhalb von 24 Stunden an Werktagen."
  }
};

export function findService(slug: string): GalabauService | undefined {
  return galabau.services.find((service) => service.slug === slug);
}

export default galabau;
