// Generated by Website Factory. Update via the factory pipeline, not by hand.

export type Review = {
  author: string;
  rating: number;
  text: string;
  time: string;
};

export type ReviewsData = {
  overallRating: number;
  totalRatings: number;
  reviews: Review[];
};

export const reviewsDataGeneratedFromFactory = true;

export const reviewsData: ReviewsData = {
  "overallRating": 4.2,
  "totalRatings": 5,
  "reviews": [
    {
      "author": "Max Fein",
      "rating": 5,
      "text": "Wir waren mit Herr Gashi sehr Zufrieden.",
      "time": "vor 9 Monaten"
    },
    {
      "author": "Albi Salku",
      "rating": 5,
      "text": "👍👍👍👍",
      "time": "vor 3 Jahren"
    }
  ]
};
